name: eshoponweb-ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build Public API
        run: dotnet build src/PublicApi/PublicApi.csproj --configuration Release --no-restore

      - name: Build Order API
        run: dotnet build src/OrderApi/OrderApi.csproj --configuration Release --no-restore

      - name: Build Web
        run: dotnet build src/Web/Web.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
