name: eshoponweb-container-aks

on:
  push:
    branches: [capitulo6]
  pull_request:
    branches: [capitulo6]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push - Web
        run: |
          docker build --tag ${{ secrets.ACR_SERVER }}/eshoponweb-web:latest --tag ${{ secrets.ACR_SERVER }}/eshoponweb-web:${{ github.sha }} -f ./src/Web/Dockerfile .
          docker push ${{ secrets.ACR_SERVER }}/eshoponweb-web:latest
          docker push ${{ secrets.ACR_SERVER }}/eshoponweb-web:${{ github.sha }}

      - name: Build and Push - PublicApi
        run: |
          docker build --tag ${{ secrets.ACR_SERVER }}/eshoponweb-publicapi:latest --tag ${{ secrets.ACR_SERVER }}/eshoponweb-publicapi:${{ github.sha }} -f ./src/PublicApi/Dockerfile .
          docker push ${{ secrets.ACR_SERVER }}/eshoponweb-publicapi:latest
          docker push ${{ secrets.ACR_SERVER }}/eshoponweb-publicapi:${{ github.sha }}

      - name: Build and Push - OrderApi
        run: |
          docker build --tag ${{ secrets.ACR_SERVER }}/eshoponweb-orderapi:latest --tag ${{ secrets.ACR_SERVER }}/eshoponweb-orderapi:${{ github.sha }} -f ./src/OrderApi/Dockerfile .
          docker push ${{ secrets.ACR_SERVER }}/eshoponweb-orderapi:latest
          docker push ${{ secrets.ACR_SERVER }}/eshoponweb-orderapi:${{ github.sha }}

      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: aks-cluster
          resource-group: rg-eshoponweb-cloud

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            src/PaaSDeploy/eshoponweb.yaml
          images: |
            ${{ secrets.ACR_SERVER }}/eshoponweb-web:${{ github.sha }}
            ${{ secrets.ACR_SERVER }}/eshoponweb-publicapi:${{ github.sha }}
            ${{ secrets.ACR_SERVER }}/eshoponweb-orderapi:${{ github.sha }}

      - name: Alterar ENV APPCONFIG_CONNECTIONSTRING dos Deployments
        run: |
          kubectl set env deployment/web-deploy APPCONFIG_CONNECTIONSTRING=${{ secrets.APPCONFIG_CONNECTIONSTRING }}
          kubectl set env deployment/publicapi-deploy APPCONFIG_CONNECTIONSTRING=${{ secrets.APPCONFIG_CONNECTIONSTRING }}
          kubectl set env deployment/orderapi-deploy APPCONFIG_CONNECTIONSTRING=${{ secrets.APPCONFIG_CONNECTIONSTRING }}
